# 使用自制的python3.12 包含ffmpeg rocketmq的基础镜像
FROM swr.cn-east-3.myhuaweicloud.com/freeuuu/python312-ffmpeg:2.3


# 复制代码文件
COPY . /app
WORKDIR /app

#从requirements.txt里安装依赖
RUN pip install --timeout=600 \
    -r requirements.txt \
    -i https://mirrors.aliyun.com/pypi/simple/

# 设置系统时区为上海
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app/src

# 设置 PYTHONPATH，让 Celery 可以 import 项目
ENV PYTHONPATH=/app/src

# Celery worker 启动命令
CMD ["celery", "-A", "celery_mq.celery_app", "worker", "--hostname=sprite_test@%%h", "--loglevel=INFO", "--queues=test_sprite_queue", "--concurrency=10"]