# 使用自制的python3.12 包含ffmpeg rocketmq的基础镜像
FROM python:3.12

# 复制代码文件
COPY . /app
WORKDIR /app

#从requirements.txt里安装依赖
RUN pip install --timeout=600 \
    -r requirements.txt \
    -i https://mirrors.aliyun.com/pypi/simple/

WORKDIR /app/src
# 设置系统时区为上海
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 暴露端口
EXPOSE 5000


# 启动命令
CMD ["python", "core/dispatcher/run.py"]