# 使用自制的 python3.12 + ffmpeg + rocketmq 基础镜像
FROM swr.cn-east-3.myhuaweicloud.com/freeuuu/python312-ffmpeg:2.1

# 复制代码文件
COPY . /app
WORKDIR /app/src

# 如果你有 requirements.txt，安装依赖
RUN pip install --timeout=600 -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 设置 PYTHONPATH，让 Celery 可以 import 项目
ENV PYTHONPATH=/app/src

# Celery worker 启动命令
CMD ["celery", "-A", "celery_mq.celery_app", "worker", "--loglevel=INFO", "--queue=video_queue", "--concurrency=4"]