audio_language: zh-CN
audio_speed: normal
audio_type: remote
background_music: C:\Job\MoneyPrinterPlus\bgmusic\1.mp3
background_music_dir: C:\Job\MoneyPrinterPlus\bgmusic
background_music_volume: 0.3
captioning_lines: 2
enable_background_music: true
enable_subtitles: true
enable_video_transition_effect: true
recognition_audio_type: local
scene_number: 1
subtitle_border_color: '#000000'
subtitle_border_width: 0
subtitle_color: '#FFFFFF'
subtitle_font: Songti SC Bold
subtitle_font_size: 6
subtitle_position: 2
video_fps: 20
video_layout: portrait
video_scene_folder_1: C:\Editing\MMD Resource\Video
video_scene_text_1: C:\AI\ComfyUI_windows_portable\README_VERY_IMPORTANT.txt
video_segment_max_length: 10
video_segment_min_length: 5
video_size: 1080x1920
video_transition_effect_duration: '1'
video_transition_effect_type: xfade
video_transition_effect_value: fade
videos_count: 1
