from __future__ import annotations

from typing import Literal


voice_options_big = {
    #通用
    "冷酷哥哥": "zh_male_lengkugege_emo_v2_mars_bigtts",
    "甜心小美": "zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
    "高冷御姐": "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    "傲娇霸总": "zh_male_aojiaobazong_emo_v2_mars_bigtts",
    "广州德哥": "zh_male_guangzhoudege_emo_mars_bigtts",
    "京腔侃爷": "zh_male_jingqiangkanye_emo_mars_bigtts",
    "邻居阿姨": "zh_female_linjuayi_emo_v2_mars_bigtts",
    "优柔公子": "zh_male_yourougongzi_emo_v2_mars_bigtts",
    "儒雅男友": "zh_male_ruyayichen_emo_v2_mars_bigtts",
    "俊朗男友": "zh_male_junlangnanyou_emo_v2_mars_bigtts",
    "北京小爷": "zh_male_beijingxiaoye_emo_v2_mars_bigtts",
    "柔美女友": "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    "阳光青年": "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    "魅力女友": "zh_female_meilinvyou_emo_v2_mars_bigtts",
    "爽快思思": "zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
    #趣味口音
    "沪普男": "zh_male_hupunan_mars_bigtts",
    "粤语小溏": "zh_female_yueyunv_mars_bigtts",
    "鲁班七号": "zh_male_lubanqihao_mars_bigtts",
    "林潇": "zh_female_yangmi_mars_bigtts",
    "玲玲姐姐": "zh_female_linzhiling_mars_bigtts",
    "春日部姐姐": "zh_female_jiyejizi2_mars_bigtts",
    "唐僧": "zh_male_tangseng_mars_bigtts",
    "庄周": "zh_male_zhuangzhou_mars_bigtts",
    "猪八戒": "zh_male_zhubajie_mars_bigtts",
    "感冒电音姐姐": "zh_female_ganmaodianyin_mars_bigtts",
    "直率英子": "zh_female_naying_mars_bigtts",
    "女雷神": "zh_female_leidian_mars_bigtts",
    "豫州子轩": "zh_male_yuzhouzixuan_moon_bigtts",
    "呆萌川妹": "zh_female_daimengchuanmei_moon_bigtts",
    "广西远舟": "zh_male_guangxiyuanzhou_moon_bigtts",
    "双节棍小哥": "zh_male_zhoujielun_emo_v2_mars_bigtts",
    "湾湾小何": "zh_female_wanwanxiaohe_moon_bigtts",
    "湾区大叔": "zh_female_wanqudashu_moon_bigtts",
    "浩宇小哥": "zh_male_haoyuxiaoge_moon_bigtts",
    "妹坨洁儿": "zh_female_meituojieer_moon_bigtts",
    # 角色扮演
    "纯真少女": "ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",
    "奶气小生": "ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",
    "精灵向导": "ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob",
    "闷油瓶小哥": "ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",
    "黯刃秦主": "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",
    "霸道总裁": "ICL_zh_male_badaozongcai_v1_tob",
    "妩媚可人": "ICL_zh_female_ganli_v1_tob",
    "邪魅御姐": "ICL_zh_female_xiangliangya_v1_tob",
    "嚣张小哥": "ICL_zh_male_ms_tob",
    "油腻大叔": "ICL_zh_male_you_tob",
    "孤傲公子": "ICL_zh_male_guaogongzi_v1_tob",
    "胡子叔叔": "ICL_zh_male_huzi_v1_tob",
    "性感魅惑": "ICL_zh_female_luoqing_v1_tob",
    "病弱公子": "ICL_zh_male_bingruogongzi_tob",
    "邪魅女王": "ICL_zh_female_bingjiao3_tob",
    "傲慢青年": "ICL_zh_male_aomanqingnian_tob",
    "醋精男生": "ICL_zh_male_cujingnansheng_tob",
    "爽朗少年": "ICL_zh_male_shuanglangshaonian_tob",
    "撒娇男友": "ICL_zh_male_sajiaonanyou_tob",
    "温柔男友": "ICL_zh_male_wenrounanyou_tob",
    "温顺少年": "ICL_zh_male_wenshunshaonian_tob",
    "粘人男友": "ICL_zh_male_naigounanyou_tob",
    "撒娇男生": "ICL_zh_male_sajiaonansheng_tob",
    "活泼男友": "ICL_zh_male_huoponanyou_tob",
    "甜系男友": "ICL_zh_male_tianxinanyou_tob",
    "活力青年": "ICL_zh_male_huoliqingnian_tob",
    "开朗青年": "ICL_zh_male_kailangqingnian_tob",
    "冷漠兄长": "ICL_zh_male_lengmoxiongzhang_tob",
    "天才同桌": "ICL_zh_male_tiancaitongzhuo_tob",
    "翩翩公子": "ICL_zh_male_pianpiangongzi_tob",
    "懵懂青年": "ICL_zh_male_mengdongqingnian_tob",
    "冷脸兄长": "ICL_zh_male_lenglianxiongzhang_tob",
    "病娇少年": "ICL_zh_male_bingjiaoshaonian_tob",
    "病娇男友": "ICL_zh_male_bingjiaonanyou_tob",
    "病弱少年": "ICL_zh_male_bingruoshaonian_tob",
    "意气少年": "ICL_zh_male_yiqishaonian_tob",
    "干净少年": "ICL_zh_male_ganjingshaonian_tob",
    "冷漠男友": "ICL_zh_male_lengmonanyou_tob",
    "精英青年": "ICL_zh_male_jingyingqingnian_tob",
    "热血少年": "ICL_zh_male_rexueshaonian_tob",
    "清爽少年": "ICL_zh_male_qingshuangshaonian_tob",
    "中二青年": "ICL_zh_male_zhongerqingnian_tob",
    "凌云青年": "ICL_zh_male_lingyunqingnian_tob",
    "自负青年": "ICL_zh_male_zifuqingnian_tob",
    "不羁青年": "ICL_zh_male_bujiqingnian_tob",
    "儒雅君子": "ICL_zh_male_ruyajunzi_tob",
    "低音沉郁": "ICL_zh_male_diyinchenyu_tob",
    "冷脸学霸": "ICL_zh_male_lenglianxueba_tob",
    "儒雅总裁": "ICL_zh_male_ruyazongcai_tob",
    "深沉总裁": "ICL_zh_male_shenchenzongcai_tob",
    "小侯爷": "ICL_zh_male_xiaohouye_tob",
    "孤高公子": "ICL_zh_male_gugaogongzi_tob",
    "仗剑君子": "ICL_zh_male_zhangjianjunzi_tob",
    "温润学者": "ICL_zh_male_wenrunxuezhe_tob",
    "亲切青年": "ICL_zh_male_qinqieqingnian_tob",
    "温柔学长": "ICL_zh_male_wenrouxuezhang_tob",
    "高冷总裁": "ICL_zh_male_gaolengzongcai_tob",
    "冷峻高智": "ICL_zh_male_lengjungaozhi_tob",
    "孱弱少爷": "ICL_zh_male_chanruoshaoye_tob",
    "自信青年": "ICL_zh_male_zixinqingnian_tob",
    "青涩青年": "ICL_zh_male_qingseqingnian_tob",
    "学霸同桌": "ICL_zh_male_xuebatongzhuo_tob",
    "冷傲总裁": "ICL_zh_male_lengaozongcai_tob",
    "元气少年": "ICL_zh_male_yuanqishaonian_tob",
    "洒脱青年": "ICL_zh_male_satuoqingnian_tob",
    "直率青年": "ICL_zh_male_zhishuaiqingnian_tob",
    "斯文青年": "ICL_zh_male_siwenqingnian_tob",
    "俊逸公子": "ICL_zh_male_junyigongzi_tob",
    "仗剑侠客": "ICL_zh_male_zhangjianxiake_tob",
    "机甲智能": "ICL_zh_male_jijiaozhineng_tob",
    "奶气萌娃": "zh_male_naiqimengwa_mars_bigtts",
    "婆婆": "zh_female_popo_mars_bigtts",
    "高冷御姐2": "zh_female_gaolengyujie_moon_bigtts",
    "傲娇霸总2": "zh_male_aojiaobazong_moon_bigtts",
    "魅力女友2": "zh_female_meilinvyou_moon_bigtts",
    "深夜播客": "zh_male_shenyeboke_moon_bigtts",
    "柔美女友2": "zh_female_sajiaonvyou_moon_bigtts",
    "撒娇学妹": "zh_female_yuanqinvyou_moon_bigtts",
    "病弱少女": "ICL_zh_female_bingruoshaonv_tob",
    "活泼女孩": "ICL_zh_female_huoponvhai_tob",
    "东方浩然": "zh_male_dongfanghaoran_moon_bigtts",
    "绿茶小哥": "ICL_zh_male_lvchaxiaoge_tob",
    "娇弱萝莉": "ICL_zh_female_jiaoruoluoli_tob",
    "冷淡疏离": "ICL_zh_male_lengdanshuli_tob",
    "憨厚敦实": "ICL_zh_male_hanhoudunshi_tob",
    "活泼刁蛮": "ICL_zh_female_huopodiaoman_tob",
    "固执病娇": "ICL_zh_male_guzhibingjiao_tob",
    "撒娇粘人": "ICL_zh_male_sajiaonianren_tob",
    "傲慢娇声": "ICL_zh_female_aomanjiaosheng_tob",
    "潇洒随性": "ICL_zh_male_xiaosasuixing_tob",
    "诡异神秘": "ICL_zh_male_guiyishenmi_tob",
    "儒雅才俊": "ICL_zh_male_ruyacaijun_tob",
    "正直青年": "ICL_zh_male_zhengzhiqingnian_tob",
    "娇憨女王": "ICL_zh_female_jiaohannvwang_tob",
    "病娇萌妹": "ICL_zh_female_bingjiaomengmei_tob",
    "青涩小生": "ICL_zh_male_qingsenaigou_tob",
    "纯真学弟": "ICL_zh_male_chunzhenxuedi_tob",
    "优柔帮主": "ICL_zh_male_youroubangzhu_tob",
    "优柔公子2": "ICL_zh_male_yourougongzi_tob",
    "调皮公主": "ICL_zh_female_tiaopigongzhu_tob",
    "贴心男友": "ICL_zh_male_tiexinnanyou_tob",
    "少年将军": "ICL_zh_male_shaonianjiangjun_tob",
    "病娇哥哥": "ICL_zh_male_bingjiaogege_tob",
    "学霸男同桌": "ICL_zh_male_xuebanantongzhuo_tob",
    "幽默叔叔": "ICL_zh_male_youmoshushu_tob",
    "假小子": "ICL_zh_female_jiaxiaozi_tob",
    "温柔男同桌": "ICL_zh_male_wenrounantongzhuo_tob",
    "幽默大爷": "ICL_zh_male_youmodaye_tob",
    "枕边低语": "ICL_zh_male_asmryexiu_tob",
    "神秘法师": "ICL_zh_male_shenmifashi_tob",
    "娇喘女声": "zh_female_jiaochuan_mars_bigtts",
    "开朗弟弟": "zh_male_livelybro_mars_bigtts",
    "谄媚女声": "zh_female_flattery_mars_bigtts",
    "冷峻上司": "ICL_zh_male_lengjunshangsi_tob",
    #角色扮演 S2S-SC
    "醋精男友": "ICL_zh_male_cujingnanyou_tob",
    "风发少年": "ICL_zh_male_fengfashaonian_tob",
    "磁性男嗓": "ICL_zh_male_cixingnansang_tob",
    "成熟总裁": "ICL_zh_male_chengshuzongcai_tob",
    "傲娇精英": "ICL_zh_male_aojiaojingying_tob",
    "傲娇公子": "ICL_zh_male_aojiaogongzi_tob",
    "霸道少爷": "ICL_zh_male_badaoshaoye_tob",
    "腹黑公子": "ICL_zh_male_fuheigongzi_tob",
    "暖心学姐": "ICL_zh_female_nuanxinxuejie_tob",
    "可爱女生": "ICL_zh_female_keainvsheng_tob",
    "成熟姐姐": "ICL_zh_female_chengshujiejie_tob",
    "病娇姐姐": "ICL_zh_female_bingjiaojiejie_tob",
    "妩媚御姐": "ICL_zh_female_wumeiyujie_tob",
    "傲娇女友": "ICL_zh_female_aojiaonvyou_tob",
    "贴心女友": "ICL_zh_female_tiexinnvyou_tob",
    "性感御姐": "ICL_zh_female_xingganyujie_tob",
    "病娇弟弟": "ICL_zh_male_bingjiaodidi_tob",
    "傲慢少爷": "ICL_zh_male_aomanshaoye_tob",
    "傲气凌人": "ICL_zh_male_aiqilingren_tob",
    "病娇白莲": "ICL_zh_male_bingjiaobailian_tob",
    #客服
    "理性圆子": "ICL_zh_female_lixingyuanzi_cs_tob",
    "清甜桃桃": "ICL_zh_female_qingtiantaotao_cs_tob",
    "清晰小雪": "ICL_zh_female_qingxixiaoxue_cs_tob",
    "清甜莓莓": "ICL_zh_female_qingtianmeimei_cs_tob",
    "开朗婷婷": "ICL_zh_female_kailangtingting_cs_tob",
    "清新沐沐": "ICL_zh_male_qingxinmumu_cs_tob",
    "爽朗小阳": "ICL_zh_male_shuanglangxiaoyang_cs_tob",
    "清新波波": "ICL_zh_male_qingxinbobo_cs_tob",
    "温婉珊珊": "ICL_zh_female_wenwanshanshan_cs_tob",
    "甜美小雨": "ICL_zh_female_tianmeixiaoyu_cs_tob",
    "热情艾娜": "ICL_zh_female_reqingaina_cs_tob",
    "甜美小橘": "ICL_zh_female_tianmeixiaoju_cs_tob",
    "沉稳明仔": "ICL_zh_male_chenwenmingzai_cs_tob",
    "亲切小卓": "ICL_zh_male_qinqiexiaozhuo_cs_tob",
    "灵动欣欣": "ICL_zh_female_lingdongxinxin_cs_tob",
    "乖巧可儿": "ICL_zh_female_guaiqiaokeer_cs_tob",
    "暖心茜茜": "ICL_zh_female_nuanxinqianqian_cs_tob",
    "软萌团子": "ICL_zh_female_ruanmengtuanzi_cs_tob",
    "阳光洋洋": "ICL_zh_male_yangguangyangyang_cs_tob",
    "软萌糖糖": "ICL_zh_female_ruanmengtangtang_cs_tob",
    "秀丽倩倩": "ICL_zh_female_xiuliqianqian_cs_tob",
    "开心小鸿": "ICL_zh_female_kaixinxiaohong_cs_tob",
    "轻盈朵朵": "ICL_zh_female_qingyingduoduo_cs_tob",
    "暖阳女声": "zh_female_kefunvsheng_mars_bigtts",
    #视频配音
    "悠悠君子": "zh_male_M100_conversation_wvae_bigtts",
    "文静毛毛": "zh_female_maomao_conversation_wvae_bigtts",
    "倾心少女": "ICL_zh_female_qiuling_v1_tob",
    "醇厚低音": "ICL_zh_male_buyan_v1_tob",
    "咆哮小哥": "ICL_zh_male_BV144_paoxiaoge_v1_tob",
    "和蔼奶奶": "ICL_zh_female_heainainai_tob",
    "邻居阿姨2": "ICL_zh_female_linjuayi_tob",
    "温柔小雅": "zh_female_wenrouxiaoya_moon_bigtts",
    "天才童声": "zh_male_tiancaitongsheng_mars_bigtts",
    "猴哥": "zh_male_sunwukong_mars_bigtts",
    "熊二": "zh_male_xionger_mars_bigtts",
    "佩奇猪": "zh_female_peiqi_mars_bigtts",
    "武则天": "zh_female_wuzetian_mars_bigtts",
    "顾姐": "zh_female_gujie_mars_bigtts",
    "樱桃丸子": "zh_female_yingtaowanzi_mars_bigtts",
    "广告解说": "zh_male_chunhui_mars_bigtts",
    "少儿故事": "zh_female_shaoergushi_mars_bigtts",
    "四郎": "zh_male_silang_mars_bigtts",
    "俏皮女声": "zh_female_qiaopinvsheng_mars_bigtts",
    "懒音绵宝": "zh_male_lanxiaoyang_mars_bigtts",
    "亮嗓萌仔": "zh_male_dongmanhaimian_mars_bigtts",
    "磁性解说男声": "zh_male_jieshuonansheng_mars_bigtts",
    "鸡汤妹妹": "zh_female_jitangmeimei_mars_bigtts",
    "贴心女声": "zh_female_tiexinnvsheng_mars_bigtts",
    "萌丫头": "zh_female_mengyatou_mars_bigtts",
    #新增
    "Vivi": "zh_female_vv_mars_bigtts",
    "机灵小伙": "ICL_zh_male_shenmi_v1_tob",
    "温暖少年": "ICL_zh_male_yangyang_v1_tob",
    "开朗轻快": "ICL_zh_male_kailangqingkuai_tob",
    "擎苍": "zh_male_qingcang_mars_bigtts",
    "心灵鸡汤": "zh_female_xinlingjitang_moon_bigtts",
    "甜美悦悦": "zh_female_tianmeiyueyue_moon_bigtts",
    "天才少女": "BV421_streaming",
}

voice_options_small = {
    # 通用场景
    "灿灿 2.0": "BV700_V2_streaming",
    "炀炀": "BV705_streaming",
    "擎苍 2.0": "BV701_V2_streaming",
    "通用女声 2.0": "BV001_V2_streaming",
    "灿灿": "BV700_streaming",
    "超自然音色-梓梓2.0": "BV406_V2_streaming",
    "超自然音色-梓梓": "BV406_streaming",
    "超自然音色-燃燃2.0": "BV407_V2_streaming",
    "超自然音色-燃燃": "BV407_streaming",
    "通用女声": "BV001_streaming",
    "通用男声": "BV002_streaming",
    "天才少女": "BV421_streaming",
    # 有声阅读
    "擎苍": "BV701_streaming",
    "阳光青年": "BV123_streaming",
    "反卷青年": "BV120_streaming",
    "通用赘婿": "BV119_streaming",
    "古风少御": "BV115_streaming",
    "霸气青叔": "BV107_streaming",
    "质朴青年": "BV100_streaming",
    "温柔淑女": "BV104_streaming",
    "开朗青年": "BV004_streaming",
    "甜宠少御": "BV113_streaming",
    "儒雅青年": "BV102_streaming",
    # 智能助手
    "甜美小源": "BV405_streaming",
    "亲切女声": "BV007_streaming",
    "知性女声": "BV009_streaming",
    "诚诚": "BV419_streaming",
    "童童": "BV415_streaming",
    "亲切男声": "BV008_streaming",
    # 视频配音
    "译制片男声": "BV408_streaming",
    "懒小羊": "BV426_streaming",
    "清新文艺女声": "BV428_streaming",
    "鸡汤女声": "BV403_streaming",
    "智慧老者": "BV158_streaming",
    "慈爱姥姥": "BV157_streaming",
    "说唱小哥": "BR001_streaming",
    "活力解说男": "BV410_streaming",
    "影视解说小帅": "BV411_streaming",
    "解说小帅-多情感": "BV437_streaming",
    "影视解说小美": "BV412_streaming",
    "纨绔青年": "BV159_streaming",
    "直播一姐": "BV418_streaming",
    "沉稳解说男": "BV142_streaming",
    "潇洒青年": "BV143_streaming",
    "阳光男声": "BV056_streaming",
    "活泼女声": "BV005_streaming",
    "小萝莉": "BV064_streaming",
    # 特色音色
    "奶气萌娃": "BV051_streaming",
    "动漫海绵": "BV063_streaming",
    "动漫海星": "BV417_streaming",
    "动漫小新": "BV050_streaming",
    "天才童声": "BV061_streaming",
    # 广告配音
    "促销男声": "BV401_streaming",
    "促销女声": "BV402_streaming",
    "磁性男声": "BV006_streaming",
    # 新闻播报
    "新闻女声": "BV011_streaming",
    "新闻男声": "BV012_streaming",
    # 教育场景
    "知性姐姐-双语": "BV034_streaming",
    "温柔小哥": "BV033_streaming",
}

voice_options = {
    "big": voice_options_big,
    "small": voice_options_small,
}

volcano_voice_options = voice_options

character_options = {**voice_options_big, **voice_options_small}

voice_model_type_options = ("big", "small")


def get_volcano_voice_type(voice_character: str) -> Literal["big", "small"]:
    if voice_character in voice_options_small:
        return "small"
    if voice_character in voice_options_big:
        return "big"
    raise KeyError(f"Unknown volcovoice character: {voice_character}")


def get_voice_options(model_type: str = "all") -> dict[str, str]:
    normalized = (model_type or "all").lower()
    if normalized == "all":
        return character_options
    if normalized == "big":
        return voice_options_big
    if normalized == "small":
        return voice_options_small
    raise ValueError("model_type must be one of: all, big, small")

__all__ = [
    'voice_options_big',
    'voice_options_small',
    'voice_options',
    'volcano_voice_options',
    'character_options',
    'voice_model_type_options',
    'get_volcano_voice_type',
    'get_voice_options',
    'voice_enums_meta',
]

if __name__ == "__main__":
    # for name, liter in character_options.items():
    #     print(name, liter)
    print(f"big keys: {list(voice_options_big.keys())[:5]} ...")
    print(f"small keys: {list(voice_options_small.keys())[:5]} ...")
    print(character_options.keys())
    print(f"length: {len(character_options)}")


voice_enums_meta = {
    'Vivi': {'gender': '女', 'age': '青年'},
    '不羁青年': {'gender': '女', 'age': '青年'},
    '东方浩然': {'gender': '女', 'age': '青年'},
    '中二青年': {'gender': '女', 'age': '青年'},
    '乖巧可儿': {'gender': '女', 'age': '青年'},
    '京腔侃爷': {'gender': '男', 'age': '青年'},
    '亮嗓萌仔': {'gender': '女', 'age': '青年'},
    '亲切女声': {'gender': '女', 'age': '青年'},
    '亲切小卓': {'gender': '女', 'age': '青年'},
    '亲切男声': {'gender': '男', 'age': '青年'},
    '亲切青年': {'gender': '女', 'age': '青年'},
    '仗剑侠客': {'gender': '女', 'age': '青年'},
    '仗剑君子': {'gender': '男', 'age': '青年'},
    '优柔公子': {'gender': '男', 'age': '青年'},
    '优柔公子2': {'gender': '男', 'age': '青年'},
    '优柔帮主': {'gender': '女', 'age': '青年'},
    '低音沉郁': {'gender': '女', 'age': '青年'},
    '佩奇猪': {'gender': '儿童', 'age': '儿童'},
    '促销女声': {'gender': '女', 'age': '青年'},
    '促销男声': {'gender': '男', 'age': '青年'},
    '俊朗男友': {'gender': '男', 'age': '青年'},
    '俊逸公子': {'gender': '男', 'age': '青年'},
    '俏皮女声': {'gender': '女', 'age': '青年'},
    '倾心少女': {'gender': '女', 'age': '少年/少女'},
    '假小子': {'gender': '女', 'age': '青年'},
    '傲娇公子': {'gender': '男', 'age': '青年'},
    '傲娇女友': {'gender': '女', 'age': '青年'},
    '傲娇精英': {'gender': '女', 'age': '青年'},
    '傲娇霸总': {'gender': '女', 'age': '中年'},
    '傲娇霸总2': {'gender': '女', 'age': '中年'},
    '傲慢娇声': {'gender': '女', 'age': '青年'},
    '傲慢少爷': {'gender': '男', 'age': '青年'},
    '傲慢青年': {'gender': '女', 'age': '青年'},
    '傲气凌人': {'gender': '女', 'age': '青年'},
    '儒雅君子': {'gender': '男', 'age': '青年'},
    '儒雅总裁': {'gender': '女', 'age': '中年'},
    '儒雅才俊': {'gender': '女', 'age': '青年'},
    '儒雅男友': {'gender': '男', 'age': '青年'},
    '儒雅青年': {'gender': '女', 'age': '青年'},
    '元气少年': {'gender': '女', 'age': '少年/少女'},
    '冷傲总裁': {'gender': '女', 'age': '中年'},
    '冷峻上司': {'gender': '女', 'age': '中年'},
    '冷峻高智': {'gender': '女', 'age': '青年'},
    '冷淡疏离': {'gender': '女', 'age': '青年'},
    '冷漠兄长': {'gender': '女', 'age': '青年'},
    '冷漠男友': {'gender': '男', 'age': '青年'},
    '冷脸兄长': {'gender': '女', 'age': '青年'},
    '冷脸学霸': {'gender': '女', 'age': '青年'},
    '冷酷哥哥': {'gender': '男', 'age': '青年'},
    '凌云青年': {'gender': '女', 'age': '青年'},
    '动漫小新': {'gender': '儿童', 'age': '儿童'},
    '动漫海星': {'gender': '儿童', 'age': '儿童'},
    '动漫海绵': {'gender': '儿童', 'age': '儿童'},
    '北京小爷': {'gender': '男', 'age': '少年/少女'},
    '双节棍小哥': {'gender': '男', 'age': '青年'},
    '反卷青年': {'gender': '女', 'age': '青年'},
    '古风少御': {'gender': '女', 'age': '青年'},
    '可爱女生': {'gender': '女', 'age': '青年'},
    '呆萌川妹': {'gender': '女', 'age': '青年'},
    '咆哮小哥': {'gender': '男', 'age': '青年'},
    '和蔼奶奶': {'gender': '女', 'age': '老年'},
    '唐僧': {'gender': '男', 'age': '青年'},
    '嚣张小哥': {'gender': '男', 'age': '青年'},
    '四郎': {'gender': '女', 'age': '青年'},
    '固执病娇': {'gender': '女', 'age': '青年'},
    '天才同桌': {'gender': '女', 'age': '少年/少女'},
    '天才少女': {'gender': '女', 'age': '少年/少女'},
    '天才童声': {'gender': '儿童', 'age': '儿童'},
    '女雷神': {'gender': '女', 'age': '青年'},
    '奶气小生': {'gender': '男', 'age': '青年'},
    '奶气萌娃': {'gender': '儿童', 'age': '儿童'},
    '妩媚可人': {'gender': '女', 'age': '青年'},
    '妩媚御姐': {'gender': '女', 'age': '青年'},
    '妹坨洁儿': {'gender': '女', 'age': '青年'},
    '娇喘女声': {'gender': '女', 'age': '青年'},
    '娇弱萝莉': {'gender': '儿童', 'age': '儿童'},
    '娇憨女王': {'gender': '女', 'age': '青年'},
    '婆婆': {'gender': '女', 'age': '老年'},
    '孤傲公子': {'gender': '男', 'age': '青年'},
    '孤高公子': {'gender': '男', 'age': '青年'},
    '学霸同桌': {'gender': '女', 'age': '少年/少女'},
    '学霸男同桌': {'gender': '男', 'age': '少年/少女'},
    '孱弱少爷': {'gender': '男', 'age': '青年'},
    '小侯爷': {'gender': '男', 'age': '青年'},
    '小萝莉': {'gender': '儿童', 'age': '儿童'},
    '少儿故事': {'gender': '儿童', 'age': '儿童'},
    '少年将军': {'gender': '女', 'age': '少年/少女'},
    '干净少年': {'gender': '女', 'age': '少年/少女'},
    '幽默叔叔': {'gender': '男', 'age': '中年'},
    '幽默大爷': {'gender': '男', 'age': '老年'},
    '广告解说': {'gender': '女', 'age': '青年'},
    '广州德哥': {'gender': '男', 'age': '青年'},
    '广西远舟': {'gender': '女', 'age': '青年'},
    '庄周': {'gender': '男', 'age': '青年'},
    '开心小鸿': {'gender': '女', 'age': '青年'},
    '开朗婷婷': {'gender': '女', 'age': '青年'},
    '开朗弟弟': {'gender': '女', 'age': '青年'},
    '开朗轻快': {'gender': '女', 'age': '青年'},
    '开朗青年': {'gender': '女', 'age': '青年'},
    '影视解说小帅': {'gender': '男', 'age': '青年'},
    '影视解说小美': {'gender': '女', 'age': '青年'},
    '心灵鸡汤': {'gender': '女', 'age': '青年'},
    '性感御姐': {'gender': '女', 'age': '青年'},
    '性感魅惑': {'gender': '女', 'age': '青年'},
    '悠悠君子': {'gender': '男', 'age': '青年'},
    '意气少年': {'gender': '女', 'age': '少年/少女'},
    '感冒电音姐姐': {'gender': '女', 'age': '青年'},
    '慈爱姥姥': {'gender': '女', 'age': '老年'},
    '憨厚敦实': {'gender': '女', 'age': '青年'},
    '懒小羊': {'gender': '女', 'age': '青年'},
    '懒音绵宝': {'gender': '女', 'age': '青年'},
    '懵懂青年': {'gender': '女', 'age': '青年'},
    '成熟姐姐': {'gender': '女', 'age': '青年'},
    '成熟总裁': {'gender': '女', 'age': '中年'},
    '撒娇学妹': {'gender': '女', 'age': '少年/少女'},
    '撒娇男友': {'gender': '男', 'age': '青年'},
    '撒娇男生': {'gender': '男', 'age': '青年'},
    '撒娇粘人': {'gender': '女', 'age': '青年'},
    '擎苍': {'gender': '女', 'age': '青年'},
    '擎苍 2.0': {'gender': '女', 'age': '青年'},
    '文静毛毛': {'gender': '女', 'age': '青年'},
    '斯文青年': {'gender': '女', 'age': '青年'},
    '新闻女声': {'gender': '女', 'age': '青年'},
    '新闻男声': {'gender': '男', 'age': '青年'},
    '春日部姐姐': {'gender': '女', 'age': '青年'},
    '智慧老者': {'gender': '男', 'age': '老年'},
    '暖心学姐': {'gender': '女', 'age': '青年'},
    '暖心茜茜': {'gender': '女', 'age': '青年'},
    '暖阳女声': {'gender': '女', 'age': '青年'},
    '机灵小伙': {'gender': '男', 'age': '青年'},
    '机甲智能': {'gender': '女', 'age': '青年'},
    '枕边低语': {'gender': '女', 'age': '青年'},
    '林潇': {'gender': '女', 'age': '青年'},
    '柔美女友': {'gender': '女', 'age': '青年'},
    '柔美女友2': {'gender': '女', 'age': '青年'},
    '樱桃丸子': {'gender': '儿童', 'age': '儿童'},
    '正直青年': {'gender': '女', 'age': '青年'},
    '武则天': {'gender': '女', 'age': '青年'},
    '沉稳明仔': {'gender': '女', 'age': '青年'},
    '沉稳解说男': {'gender': '男', 'age': '青年'},
    '沪普男': {'gender': '男', 'age': '青年'},
    '油腻大叔': {'gender': '男', 'age': '中年'},
    '洒脱青年': {'gender': '女', 'age': '青年'},
    '活力解说男': {'gender': '男', 'age': '青年'},
    '活力青年': {'gender': '女', 'age': '青年'},
    '活泼刁蛮': {'gender': '女', 'age': '青年'},
    '活泼女声': {'gender': '女', 'age': '青年'},
    '活泼女孩': {'gender': '女', 'age': '青年'},
    '活泼男友': {'gender': '男', 'age': '青年'},
    '浩宇小哥': {'gender': '男', 'age': '青年'},
    '深夜播客': {'gender': '女', 'age': '青年'},
    '深沉总裁': {'gender': '女', 'age': '中年'},
    '清新文艺女声': {'gender': '女', 'age': '青年'},
    '清新沐沐': {'gender': '女', 'age': '青年'},
    '清新波波': {'gender': '女', 'age': '青年'},
    '清晰小雪': {'gender': '女', 'age': '青年'},
    '清爽少年': {'gender': '女', 'age': '少年/少女'},
    '清甜桃桃': {'gender': '女', 'age': '青年'},
    '清甜莓莓': {'gender': '女', 'age': '青年'},
    '温婉珊珊': {'gender': '女', 'age': '青年'},
    '温暖少年': {'gender': '女', 'age': '少年/少女'},
    '温柔学长': {'gender': '女', 'age': '青年'},
    '温柔小哥': {'gender': '男', 'age': '青年'},
    '温柔小雅': {'gender': '女', 'age': '青年'},
    '温柔淑女': {'gender': '女', 'age': '青年'},
    '温柔男友': {'gender': '男', 'age': '青年'},
    '温柔男同桌': {'gender': '男', 'age': '少年/少女'},
    '温润学者': {'gender': '男', 'age': '青年'},
    '温顺少年': {'gender': '女', 'age': '少年/少女'},
    '湾区大叔': {'gender': '男', 'age': '中年'},
    '湾湾小何': {'gender': '女', 'age': '青年'},
    '潇洒随性': {'gender': '女', 'age': '青年'},
    '潇洒青年': {'gender': '女', 'age': '青年'},
    '灵动欣欣': {'gender': '女', 'age': '青年'},
    '灿灿': {'gender': '女', 'age': '青年'},
    '灿灿 2.0': {'gender': '女', 'age': '青年'},
    '炀炀': {'gender': '女', 'age': '青年'},
    '热情艾娜': {'gender': '女', 'age': '青年'},
    '热血少年': {'gender': '女', 'age': '少年/少女'},
    '熊二': {'gender': '儿童', 'age': '儿童'},
    '爽快思思': {'gender': '女', 'age': '青年'},
    '爽朗小阳': {'gender': '女', 'age': '青年'},
    '爽朗少年': {'gender': '女', 'age': '少年/少女'},
    '猪八戒': {'gender': '儿童', 'age': '儿童'},
    '猴哥': {'gender': '男', 'age': '青年'},
    '玲玲姐姐': {'gender': '女', 'age': '青年'},
    '理性圆子': {'gender': '女', 'age': '青年'},
    '甜宠少御': {'gender': '女', 'age': '青年'},
    '甜心小美': {'gender': '女', 'age': '青年'},
    '甜系男友': {'gender': '男', 'age': '青年'},
    '甜美小橘': {'gender': '女', 'age': '青年'},
    '甜美小源': {'gender': '女', 'age': '青年'},
    '甜美小雨': {'gender': '女', 'age': '青年'},
    '甜美悦悦': {'gender': '女', 'age': '青年'},
    '病娇哥哥': {'gender': '男', 'age': '青年'},
    '病娇姐姐': {'gender': '女', 'age': '青年'},
    '病娇少年': {'gender': '女', 'age': '少年/少女'},
    '病娇弟弟': {'gender': '女', 'age': '青年'},
    '病娇男友': {'gender': '男', 'age': '青年'},
    '病娇白莲': {'gender': '女', 'age': '青年'},
    '病娇萌妹': {'gender': '女', 'age': '青年'},
    '病弱公子': {'gender': '男', 'age': '青年'},
    '病弱少女': {'gender': '女', 'age': '少年/少女'},
    '病弱少年': {'gender': '女', 'age': '少年/少女'},
    '直播一姐': {'gender': '女', 'age': '青年'},
    '直率英子': {'gender': '女', 'age': '青年'},
    '直率青年': {'gender': '女', 'age': '青年'},
    '知性女声': {'gender': '女', 'age': '青年'},
    '知性姐姐-双语': {'gender': '女', 'age': '青年'},
    '磁性男嗓': {'gender': '男', 'age': '青年'},
    '磁性男声': {'gender': '男', 'age': '青年'},
    '磁性解说男声': {'gender': '男', 'age': '青年'},
    '神秘法师': {'gender': '女', 'age': '青年'},
    '秀丽倩倩': {'gender': '女', 'age': '青年'},
    '童童': {'gender': '儿童', 'age': '儿童'},
    '粘人男友': {'gender': '男', 'age': '青年'},
    '粤语小溏': {'gender': '女', 'age': '青年'},
    '精灵向导': {'gender': '女', 'age': '青年'},
    '精英青年': {'gender': '女', 'age': '青年'},
    '纨绔青年': {'gender': '女', 'age': '青年'},
    '纯真学弟': {'gender': '女', 'age': '少年/少女'},
    '纯真少女': {'gender': '女', 'age': '少年/少女'},
    '绿茶小哥': {'gender': '男', 'age': '青年'},
    '翩翩公子': {'gender': '男', 'age': '青年'},
    '胡子叔叔': {'gender': '男', 'age': '中年'},
    '腹黑公子': {'gender': '男', 'age': '青年'},
    '自信青年': {'gender': '女', 'age': '青年'},
    '自负青年': {'gender': '女', 'age': '青年'},
    '萌丫头': {'gender': '女', 'age': '少年/少女'},
    '解说小帅-多情感': {'gender': '男', 'age': '青年'},
    '译制片男声': {'gender': '男', 'age': '青年'},
    '诚诚': {'gender': '女', 'age': '青年'},
    '诡异神秘': {'gender': '女', 'age': '青年'},
    '说唱小哥': {'gender': '男', 'age': '青年'},
    '调皮公主': {'gender': '女', 'age': '青年'},
    '谄媚女声': {'gender': '女', 'age': '青年'},
    '豫州子轩': {'gender': '女', 'age': '青年'},
    '质朴青年': {'gender': '女', 'age': '青年'},
    '贴心女友': {'gender': '女', 'age': '青年'},
    '贴心女声': {'gender': '女', 'age': '青年'},
    '贴心男友': {'gender': '男', 'age': '青年'},
    '超自然音色-梓梓': {'gender': '女', 'age': '青年'},
    '超自然音色-梓梓2.0': {'gender': '女', 'age': '青年'},
    '超自然音色-燃燃': {'gender': '女', 'age': '青年'},
    '超自然音色-燃燃2.0': {'gender': '女', 'age': '青年'},
    '软萌团子': {'gender': '儿童', 'age': '儿童'},
    '软萌糖糖': {'gender': '女', 'age': '青年'},
    '轻盈朵朵': {'gender': '女', 'age': '青年'},
    '通用女声': {'gender': '女', 'age': '青年'},
    '通用女声 2.0': {'gender': '女', 'age': '青年'},
    '通用男声': {'gender': '男', 'age': '青年'},
    '通用赘婿': {'gender': '女', 'age': '青年'},
    '邪魅女王': {'gender': '女', 'age': '青年'},
    '邪魅御姐': {'gender': '女', 'age': '青年'},
    '邻居阿姨': {'gender': '女', 'age': '中年'},
    '邻居阿姨2': {'gender': '女', 'age': '中年'},
    '醇厚低音': {'gender': '女', 'age': '青年'},
    '醋精男友': {'gender': '男', 'age': '青年'},
    '醋精男生': {'gender': '男', 'age': '青年'},
    '闷油瓶小哥': {'gender': '男', 'age': '青年'},
    '阳光洋洋': {'gender': '女', 'age': '青年'},
    '阳光男声': {'gender': '男', 'age': '青年'},
    '阳光青年': {'gender': '女', 'age': '青年'},
    '霸气青叔': {'gender': '男', 'age': '中年'},
    '霸道少爷': {'gender': '男', 'age': '青年'},
    '霸道总裁': {'gender': '女', 'age': '中年'},
    '青涩小生': {'gender': '男', 'age': '青年'},
    '青涩青年': {'gender': '女', 'age': '青年'},
    '顾姐': {'gender': '女', 'age': '青年'},
    '风发少年': {'gender': '女', 'age': '少年/少女'},
    '高冷御姐': {'gender': '女', 'age': '青年'},
    '高冷御姐2': {'gender': '女', 'age': '青年'},
    '高冷总裁': {'gender': '女', 'age': '中年'},
    '魅力女友': {'gender': '女', 'age': '青年'},
    '魅力女友2': {'gender': '女', 'age': '青年'},
    '鲁班七号': {'gender': '女', 'age': '青年'},
    '鸡汤女声': {'gender': '女', 'age': '青年'},
    '鸡汤妹妹': {'gender': '女', 'age': '青年'},
    '黯刃秦主': {'gender': '女', 'age': '青年'},
}


if __name__ == "__main__":
    # for name, liter in character_options.items():
    #     print(name, liter)
    print(f"big keys: {list(voice_options_big.keys())[:5]} ...")
    print(f"small keys: {list(voice_options_small.keys())[:5]} ...")
    print(character_options.keys())
    print(f"length: {len(character_options)}")